name: Elixir CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  mix_test:
    name: mix test (Elixir ${{matrix.elixir}} | OTP ${{matrix.otp}})
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        include:
          # - elixir: 1.0.x
          #   otp: 17.5.6.10
          # - elixir: 1.1.x
          #   otp: 17.5.6.10
          # - elixir: 1.2.x
          #   otp: 18.3.4.11
          # - elixir: 1.3.x
          #   otp: 18.3.4.11
          # - elixir: 1.4.x
          #   otp: 18.3.4.11
          # - elixir: 1.5.x
          #   otp: 18.3.4.11
          # - elixir: 1.6.x
          #   otp: 19.3.6.13
          # - elixir: 1.7.x
          #   otp: 19.3.6.13
          - elixir: 1.8.x
            otp: 20.3.8.26
          - elixir: 1.9.x
            otp: 20.3.8.26
          - elixir: 1.10.x
            otp: 21.3.8.20
          - elixir: 1.11.x
            otp: 21.3.8.20
          - elixir: 1.11.x
            otp: 22.3.4.15
          - elixir: 1.11.x
            otp: 23.2.3
          - elixir: 1.12.x
            otp: 24.0.2
            warnings_as_errors: true
            static_analysis: true
            report_coverage: true
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-elixir@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Install Dependencies
        run: |
          mix local.hex --force
          mix local.rebar --force
          mix deps.get --only test
      - run: mix compile --warnings-as-errors
        if: matrix.warnings_as_errors
      - run: mix test
      - run: |
          mix coveralls.json
          bash <(curl -s https://codecov.io/bash)
        if: matrix.report_coverage
      - run: mix hex.audit
        if: matrix.static_analysis
      - run: mix deps.get
        if: matrix.static_analysis
      - run: mix credo --strict
        env:
          MIX_ENV: dev
        if: matrix.static_analysis
      - run: mix sobelow
        if: matrix.static_analysis
      - run: mix dialyzer
        if: matrix.static_analysis
